-- Esquema inicial do Comporta. Executado automaticamente pela imagem oficial
-- do Oracle na primeira subida (arquivos em /container-entrypoint-initdb.d
-- rodam uma unica vez, quando o datafile ainda esta vazio), conectado como
-- SYSDBA no pluggable database.
--
-- O usuario da aplicacao e criado aqui mesmo, em vez de depender do
-- mecanismo APP_USER da imagem: nos testes locais a ordem de execucao entre
-- a criacao do APP_USER e os scripts desta pasta nao e garantida, e um
-- script que cria o proprio usuario nao depende dessa ordem.
--
-- A sessao do script comeca no CDB$ROOT, entao sem trocar o container o
-- usuario e os grants cairiam no container errado (o gateway conecta direto
-- no service FREEPDB1). A troca abaixo garante que tudo abaixo roda dentro
-- do pluggable database certo.
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER comporta IDENTIFIED BY "comporta_pw_troque_isto";
GRANT CONNECT, RESOURCE TO comporta;
GRANT UNLIMITED TABLESPACE TO comporta;

ALTER SESSION SET CURRENT_SCHEMA = COMPORTA;

CREATE TABLE partners (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(200) NOT NULL,
    api_key    VARCHAR2(100) NOT NULL,
    active     NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0, 1)),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_partners_api_key UNIQUE (api_key)
);

CREATE TABLE routes (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_prefix   VARCHAR2(300) NOT NULL,
    upstream_url  VARCHAR2(500) NOT NULL,
    strip_prefix  NUMBER(1) DEFAULT 1 NOT NULL CHECK (strip_prefix IN (0, 1)),
    active        NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0, 1)),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_routes_path_prefix UNIQUE (path_prefix)
);

CREATE TABLE rate_limit_policies (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id           NUMBER NOT NULL,
    route_id             NUMBER DEFAULT 0 NOT NULL,
    requests_per_minute  NUMBER NOT NULL,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_policy_partner FOREIGN KEY (partner_id) REFERENCES partners (id) ON DELETE CASCADE,
    CONSTRAINT uq_policy_partner_route UNIQUE (partner_id, route_id)
);

-- route_id = 0 representa a politica padrao do parceiro, aplicada quando ele
-- acessa uma rota sem regra dedicada (ver PolicyRepository.FindEffective).

CREATE TABLE audit_logs (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id  NUMBER NOT NULL,
    route_id    NUMBER NOT NULL,
    method      VARCHAR2(10) NOT NULL,
    path        VARCHAR2(500) NOT NULL,
    status_code NUMBER NOT NULL,
    latency_ms  NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_partner_route ON audit_logs (partner_id, route_id);
